In [1]:
pip install opencv-python==4.6.0.66

Note: you may need to restart the kernel to use updated packages.


In [2]:
#import libraries
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import cv2

In [3]:
#import image
image=cv2.imread('car.jpeg')
cv2.imshow('my image',image) #cvw.imshow() takes 2 arguments.window name and file.
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [4]:
#change image to grayscale
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray image',gray)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [5]:
#apply sharpening kernel
sharpening_kernel_1=np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
sharpened_image_1=cv2.filter2D(gray,-1,sharpening_kernel_1)
cv2.imshow('Sharpened image 1',sharpened_image_1)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [6]:
sharpening_kernel_2=np.array([[-1,-1,-1],[-1,9,-1],[-1,-1,-1]])
sharpened_image_2=cv2.filter2D(gray,-1,sharpening_kernel_2)
cv2.imshow('sharpened image 2',sharpened_image_2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [7]:
#blurring kernel
blur_kernel=np.ones((3,3))
blur_kernel


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
blurred_image=cv2.filter2D(gray,-1,blur_kernel)
cv2.imshow('Blurred image',blurred_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [9]:
#Normalize the kernel and check image
blurr_kernel=np.ones((3,3))*1/9
blurr_kernel

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [10]:
blurred_image2=cv2.filter2D(gray,-1,blurr_kernel)
cv2.imshow('blurred image',blurred_image2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
#blurring using more powerful kernel
blur_kernel_3=np.ones((8,8))
print(blur_kernel_3)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
blur_kernel_3=np.ones((8,8))*1/64
blur_kernel_3

array([[0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625]])

In [ ]:
blur_image3=cv2.filter2D(gray,-1,blur_kernel_3)
cv2.imshow("blurred image",blur_image3)
cv2.waitKey(0)
cv2.destroyAllWindows